modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory
license="MIT"
issueTrackerURL="https://github.com/a1qs/OverVaultsMillennium/issues" #optional

[[mods]] #mandatory
modId="overvaults" #mandatory
version="${file.jarVersion}" #mandatory
displayName="OverVaults" #mandatory
displayURL="https://github.com/a1qs/OverVaultsMillennium" #optional
logoFile="mbci.png" #optional
credits="Iridium for creating OverVaults" #optional
# A text field displayed in the mod UI
authors="Iridium, a1qs" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
Adds ruined vault portals to the overworld.
For all new features in Millennium Edition, see:
https://github.com/a1qs/OverVaultsMillennium'''


[[dependencies.overvaults]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[40,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.overvaults]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
